server:
  port: 8080
  servlet:
    context-path: /av
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: async-validation
#  jasypt:
#    encryptor:
#      password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#      algorithm: PBEWithHMACSHA512AndAES_256
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.example.async: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

